const fs = require('fs');

const mappings = {
  'Resource group': 'Microsoft.Resources/resourceGroups',
  'Management group': 'Microsoft.Management/managementGroups',
  'Subscription': 'Microsoft.Subscription/subscriptions',
  'Policy definition': 'Microsoft.Authorization/policyDefinitions',
  'Policy assignment': 'Microsoft.Authorization/policyAssignments',
  'Virtual Machine - Windows': 'Microsoft.Compute/virtualMachines',
  'Virtual Machine - Linux': 'Microsoft.Compute/virtualMachines',
  'VM scale set': 'Microsoft.Compute/virtualMachineScaleSets',
  'Availability set': 'Microsoft.Compute/availabilitySets',
  'Managed disk': 'Microsoft.Compute/disks',
  'Disk encryption set': 'Microsoft.Compute/diskEncryptionSets',
  'Image': 'Microsoft.Compute/images',
  'Compute gallery': 'Microsoft.Compute/galleries',
  'Proximity placement group': 'Microsoft.Compute/proximityPlacementGroups',
  'Function app': 'Microsoft.Web/sites',
  'Batch account': 'Microsoft.Batch/batchAccounts',
  'Azure Spring Apps': 'Microsoft.AppPlatform/Spring',
  'Virtual network': 'Microsoft.Network/virtualNetworks',
  'Subnet': 'Microsoft.Network/virtualNetworks/subnets',
  'Network security group': 'Microsoft.Network/networkSecurityGroups',
  'Application security group': 'Microsoft.Network/applicationSecurityGroups',
  'Public IP': 'Microsoft.Network/publicIPAddresses',
  'Public IP prefix': 'Microsoft.Network/publicIPPrefixes',
  'Load balancer': 'Microsoft.Network/loadBalancers',
  'Application Gateway': 'Microsoft.Network/applicationGateways',
  'Azure Firewall': 'Microsoft.Network/azureFirewalls',
  'Firewall policy': 'Microsoft.Network/firewallPolicies',
  'VPN Gateway': 'Microsoft.Network/virtualNetworkGateways',
  'ExpressRoute circuit': 'Microsoft.Network/expressRouteCircuits',
  'Virtual WAN': 'Microsoft.Network/virtualWans',
  'Virtual hub': 'Microsoft.Network/virtualHubs',
  'NAT Gateway': 'Microsoft.Network/natGateways',
  'Route table': 'Microsoft.Network/routeTables',
  'Private endpoint (Storage)': 'Microsoft.Network/privateEndpoints',
  'Private endpoint (Database)': 'Microsoft.Network/privateEndpoints',
  'Private endpoint (Services)': 'Microsoft.Network/privateEndpoints',
  'Private Link service': 'Microsoft.Network/privateLinkServices',
  'Traffic Manager': 'Microsoft.Network/trafficmanagerprofiles',
  'Front Door': 'Microsoft.Cdn/profiles',
  'Bastion host': 'Microsoft.Network/bastionHosts',
  'Network watcher': 'Microsoft.Network/networkWatchers',
  'DDoS protection plan': 'Microsoft.Network/ddosProtectionPlans',
  'Storage account': 'Microsoft.Storage/storageAccounts',
  'Azure Files share': 'Microsoft.Storage/storageAccounts/fileServices/shares',
  'Data Lake Storage': 'Microsoft.Storage/storageAccounts',
  'NetApp account': 'Microsoft.NetApp/netAppAccounts',
  'NetApp capacity pool': 'Microsoft.NetApp/netAppAccounts/capacityPools',
  'NetApp volume': 'Microsoft.NetApp/netAppAccounts/capacityPools/volumes',
  'App Service plan': 'Microsoft.Web/serverfarms',
  'App Service': 'Microsoft.Web/sites',
  'Static Web App': 'Microsoft.Web/staticSites',
  'API Management': 'Microsoft.ApiManagement/service',
  'SQL server': 'Microsoft.Sql/servers',
  'SQL database': 'Microsoft.Sql/servers/databases',
  'SQL elastic pool': 'Microsoft.Sql/servers/elasticPools',
  'SQL Managed Instance': 'Microsoft.Sql/managedInstances',
  'Cosmos DB account': 'Microsoft.DocumentDB/databaseAccounts',
  'MySQL server': 'Microsoft.DBforMySQL/flexibleServers',
  'PostgreSQL server': 'Microsoft.DBforPostgreSQL/flexibleServers',
  'Azure Cache for Redis': 'Microsoft.Cache/redis',
  'Kubernetes (AKS)': 'Microsoft.ContainerService/managedClusters',
  'Container registry': 'Microsoft.ContainerRegistry/registries',
  'Container instance': 'Microsoft.ContainerInstance/containerGroups',
  'Container App': 'Microsoft.App/containerApps',
  'Container Apps Environment': 'Microsoft.App/managedEnvironments',
  'Key vault': 'Microsoft.KeyVault/vaults',
  'Managed identity (user)': 'Microsoft.ManagedIdentity/userAssignedIdentities',
  'Key Vault Managed HSMs': 'Microsoft.KeyVault/managedHSMs',
  'Application Gateway WAF policy': 'Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies',
  'Service Bus namespace': 'Microsoft.ServiceBus/namespaces',
  'Service Bus queue': 'Microsoft.ServiceBus/namespaces/queues',
  'Service Bus topic': 'Microsoft.ServiceBus/namespaces/topics',
  'Event Grid topic': 'Microsoft.EventGrid/topics',
  'Event Grid domain': 'Microsoft.EventGrid/domains',
  'Event Hub namespace': 'Microsoft.EventHub/namespaces',
  'Event Hub': 'Microsoft.EventHub/namespaces/eventhubs',
  'Logic App': 'Microsoft.Logic/workflows',
  'Data Factory': 'Microsoft.DataFactory/factories',
  'SignalR service': 'Microsoft.SignalRService/signalR',
  'Notification Hub': 'Microsoft.NotificationHubs/namespaces/notificationHubs',
  'Relay': 'Microsoft.Relay/namespaces',
  'Synapse workspace': 'Microsoft.Synapse/workspaces',
  'Synapse dedicated SQL pool': 'Microsoft.Synapse/workspaces/sqlPools',
  'Data Explorer cluster': 'Microsoft.Kusto/clusters',
  'Databricks workspace': 'Microsoft.Databricks/workspaces',
  'Stream Analytics Job': 'Microsoft.StreamAnalytics/streamingjobs',
  'Fabric Capacity': 'Microsoft.Fabric/capacities',
  'Power BI Embedded': 'Microsoft.PowerBIDedicated/capacities',
  'Machine Learning workspace': 'Microsoft.MachineLearningServices/workspaces',
  'Azure AI services': 'Microsoft.CognitiveServices/accounts',
  'Azure OpenAI': 'Microsoft.CognitiveServices/accounts',
  'Azure AI Search': 'Microsoft.Search/searchServices',
  'Azure Bot Service': 'Microsoft.BotService/botServices',
  'Log Analytics workspace': 'Microsoft.OperationalInsights/workspaces',
  'Application Insights': 'Microsoft.Insights/components',
  'Action group': 'Microsoft.Insights/actionGroups',
  'Automation account': 'Microsoft.Automation/automationAccounts',
  'Recovery Services vault': 'Microsoft.RecoveryServices/vaults',
  'Blueprint': 'Microsoft.Blueprint/blueprints',
  'Cost Management export': 'Microsoft.CostManagement/exports',
  'Template Spec': 'Microsoft.Resources/templateSpecs',
  'IoT Hub': 'Microsoft.Devices/IotHubs',
  'Device Provisioning Service': 'Microsoft.Devices/provisioningServices',
  'Digital Twins': 'Microsoft.DigitalTwins/digitalTwinsInstances',
  'Host Pool': 'Microsoft.DesktopVirtualization/hostPools',
  'Application Group': 'Microsoft.DesktopVirtualization/applicationGroups',
  'Workspace': 'Microsoft.DesktopVirtualization/workspaces',
  'Scaling Plan': 'Microsoft.DesktopVirtualization/scalingPlans',
  'DevOps organization': 'Microsoft.VisualStudio/account',
  'DevTest Labs': 'Microsoft.DevTestLab/labs',
  'Azure AI Foundry account': 'Microsoft.CognitiveServices/accounts',
  'Azure AI Foundry hub': 'Microsoft.MachineLearningServices/workspaces',
  'Azure AI Foundry project': 'Microsoft.MachineLearningServices/workspaces',
  'Azure AI services account': 'Microsoft.CognitiveServices/accounts',
  'Azure OpenAI service': 'Microsoft.CognitiveServices/accounts'
};

let content = fs.readFileSync('src/data/constants.js', 'utf8');

for (const [name, provider] of Object.entries(mappings)) {
    const escapedName = name.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&');
    const regex = new RegExp(`name:\\s*['"]${escapedName}['"],`);
    content = content.replace(regex, `name: '${name}', provider: '${provider}',`);
}

fs.writeFileSync('src/data/constants.js', content, 'utf8');
console.log('constants.js updated with providers');
